name: recognizer
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - pandas
  - blast >=2.12
  - lxml
  - openpyxl
  - krona
  - wget
  - tqdm
  - xlsxwriter
  - biopython
  - requests