{% set name = "recognizer" %}
{% set version = "1.8.0" %}
{% set sha256 = "aea5ac40e5b58490c913aa0a1f6d205d54e80e11aa692b40d1fc5c59a5dbe978" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/iquasere/reCOGnizer/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0
  run_exports:
    - { { pin_subpackage(name, max_pin="x.x") } }
  script: >
    mkdir -p $PREFIX/bin && 
    mkdir -p $PREFIX/share && 
    cp recognizer.py resources/fun.tsv resources/cog2ko.tsv resources/cog2ec_recognizer.tsv $PREFIX/share &&
    chmod +x $PREFIX/share/recognizer.py &&
    ln -s $PREFIX/share/keggcharter.py $PREFIX/bin/keggcharter

requirements:
  run:
    - python
    - pandas
    - blast >=2.12
    - lxml
    - openpyxl
    - krona
    - wget
    - tqdm
    - xlsxwriter
    - requests
    - pyyaml

test:
  commands:
    - recognizer -v
    
about:
  home: https://github.com/iquasere/reCOGnizer
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A tool for domain based annotation with the COG database'
  description: |
    reCOGnizer performs domain based annotation with RPS-BLAST, using
    Hidden Markov Models from the COG database. It rebuilds the COG database
    for multithreaded annotation, organizes information regarding COG IDs
    and respective categories, obtains EC numbers using resources from the
    eggNOG database and organizes all this information into TSV and EXCEL
    files for easy handling by users or pipelines. It also produces a Krona
    plot representing the quantification of COG functions identified.
  doc_url: https://github.com/iquasere/reCOGnizer/blob/master/README.md
  dev_url: https://github.com/iquasere/reCOGnizer

extra:
  recipe-maintainers:
    - iquasere