name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: recognizer:latest
          outputs: type=docker,dest=/tmp/recognizer.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: recognizer
          path: /tmp/recognizer.tar

  use:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: recognizer
          path: /tmp

      - name: Load Docker image
        run: |
          docker load --input /tmp/recognizer.tar
          docker image ls -a

      - name: Check base entrypoint
        run: docker run recognizer /bin/bash -c "ls"

      - name: Taxonomy-free annotation
        run: docker run recognizer /bin/bash -c "mkdir resources_directory; mv reCOGnizer/ci/cdd.tar.gz resources_directory; recognizer.py -f reCOGnizer/ci/proteomes.fasta -rd resources_directory --download-resources --quiet -sd"

      - name: Taxonomy-based annotation
        run: docker run recognizer /bin/bash -c "mkdir resources_directory; mv reCOGnizer/ci/cdd.tar.gz resources_directory; recognizer.py -f reCOGnizer/ci/proteomes.fasta -rd resources_directory --tax-file reCOGnizer/ci/UPIMAPI_results.tsv --tax-col 'Taxonomic lineage (SPECIES)' --protein-id-col qseqid --download-resources --quiet  -sd"
