name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./ci/Dockerfile
          tags: recognizer:latest
          outputs: type=docker,dest=/tmp/recognizer.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: recognizer
          path: /tmp/recognizer.tar

  vanilla-annotation:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: recognizer
          path: /tmp
      - name: Load Docker image
        run: |
          docker load --input /tmp/recognizer.tar
          docker image ls -a
      - name: Default annotation
        run: docker run recognizer /bin/bash -c "recognizer -f reCOGnizer/ci/proteomes.fasta -rd resources_directory --quiet -dbs COG,TIGRFAM --test-run"

  taxonomy-based-annotation:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: recognizer
          path: /tmp
      - name: Load Docker image
        run: |
          docker load --input /tmp/recognizer.tar
          docker image ls -a
      - name: Taxonomy-based annotation
        run: docker run recognizer /bin/bash -c "recognizer -f reCOGnizer/ci/proteomes.fasta -rd resources_directory --tax-file reCOGnizer/ci/UPIMAPI_results.tsv --tax-col 'Taxonomic lineage IDs (SPECIES)' --protein-id-col qseqid --species-taxids --quiet --test-run"

  custom-database-annotation:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: recognizer
          path: /tmp
      - name: Load Docker image
        run: |
          docker load --input /tmp/recognizer.tar
          docker image ls -a
      - name: Custom database annotation
        run: docker run recognizer /bin/bash -c "tar -xzf reCOGnizer/ci/cdd.tar.gz -C resources_directory; makeprofiledb -in reCOGnizer/ci/ci.pn -out resources_directory/db; recognizer -f reCOGnizer/ci/proteomes.fasta -rd resources_directory --quiet -dbs resources_directory/db --custom-databases --test-run"
